export default {
  "$black": "#000",
  "$white": "#fff",
  "$dark-1": "#101010",
  "$dark-3": "#151515",
  "$dark-5": "#1b1b1b",
  "$dark-7": "#252525",
  "$dark-9": "#2c2c2c",
  "$gray-1": "#585858",
  "$gray-3": "#828282",
  "$gray-5": "#b4b4b5",
  "$gray-7": "#dededf",
  "$gray-9": "#f3f3f4",
  "$gold": "#dcad54",
  "$gold-hover": "#d6ab5c",
  "$page-max-width": "1200px",
  "$gutter": "8px",
  "$form-gutter": "8px",
  "$gray-light": "#f6f6f6",
  "$gray-mid": "#dfdfdf",
  "$gray": "#d9d9d9",
  "$gray2": "#5c5d5f",
  "$gray-dark": "#999",
  "$charcoal": "#1c1b19",
  "$charcoal-mid": "#2a2a2a",
  "$charcoal-light": "#404041",
  "$gold-dark": "#af9161",
  "$test": "#f2f",
  "$address-card-bg": "#d9d9d9",
  "$top-bar-height": "50px",
  "$header-height": "70px",
  "$header-font-size": "14px",
  "$header-dropdown-font-size": "14px",
  "$sm-min": "544px",
  "$md-min": "768px",
  "$lg-min": "992px",
  "$xl-min": "1200px",
  "$xs-max": "544px -1",
  "$sm-max": "768px -1",
  "$md-max": "992px -1",
  "$lg-max": "1200px -1",
  "$sm-up": "screen and (min-width: 544px)",
  "$md-up": "screen and (min-width: 768px)",
  "$lg-up": "screen and (min-width: 992px)",
  "$xl-up": "screen and (min-width: 1200px)",
  "$xs-down": "screen and (max-width: 544px -1)",
  "$sm-down": "screen and (max-width: 768px -1)",
  "$md-down": "screen and (max-width: 992px -1)",
  "$lg-down": "screen and (max-width: 1200px -1)",
  "$xs-only": "screen and (max-width: 544px -1)",
  "$sm-only": "screen and (min-width: 544px) and (max-width: 768px -1)",
  "$md-only": "screen and (min-width: 768px) and (max-width: 992px -1)",
  "$lg-only": "screen and (min-width: 992px) and (max-width: 1200px -1)",
  "$xl-only": "screen and (min-width: 1200px)",
  "$sans": "Montserrat, Helvetica, Arial, Helvetica Neue, sans-serif",
  "$serif": "Merriweather, Times, Georgia, Times New Roman, serif",
  "$font-atom": "9px",
  "$font-micro": "10px",
  "$font-micro-tiny": "11px",
  "$font-tiny": "12px",
  "$font-tiny-small": "13px",
  "$font-small": "14px",
  "$font-small-normal": "15px",
  "$font-normal": "16px",
  "$font-medium": "18px",
  "$font-medium-large": "20px",
  "$font-large": "24px",
  "$font-larger": "28px",
  "$font-big": "30px",
  "$font-bigger": "32px",
  "$font-biggest": "36px",
  "$font-biggest-fat": "40px",
  "$font-fat": "42px",
  "$font-huge": "48px",
  "$font-huger": "50px",
  "$font-mega": "60px",
  "$font-gigantic": "72px",
  "$font-impossible": "80px",
  "$font-satan": "96px",
  "$icon-xs": "16px",
  "$icon-sm": "24px",
  "$icon-md": "32px",
  "$icon-lg": "64px",
  "$icon-xl": "80px",
};